'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace AddUnboundField

    Partial Public Class _Default

        '''<summary>
        '''form1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

        '''<summary>
        '''ASPxPivotGrid1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ASPxPivotGrid1 As Global.DevExpress.Web.ASPxPivotGrid.ASPxPivotGrid

        '''<summary>
        '''fieldSalesperson control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fieldSalesperson As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

        '''<summary>
        '''fieldCountry control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fieldCountry As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

        '''<summary>
        '''fieldExtendedPrice control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fieldExtendedPrice As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

        '''<summary>
        '''fieldDiscount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fieldDiscount As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

        '''<summary>
        '''fieldDiscountAmount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fieldDiscountAmount As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

        '''<summary>
        '''fieldPriceWithDiscount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fieldPriceWithDiscount As Global.DevExpress.Web.ASPxPivotGrid.PivotGridField

        '''<summary>
        '''SqlDataSource1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SqlDataSource1 As Global.System.Web.UI.WebControls.SqlDataSource
    End Class
End Namespace
